name: Use Secrets

on:
  push:

jobs:
  api-call-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make a secret API call
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://api.github.com/zen
