name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create a dummy folder to upload
        run: |
          mkdir .dist
          echo "Ten plik został wysłany przez GitHub Actions!" > .dist/index.html

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .dist/
          server-dir: github-actions-test/
